apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: bWx0cmFpbmluZ2xhYg==
  azurestorageaccountkey: bGtneHczeDVjMVlMOWl0NjBDSDNpaThmTXdOQnc9PQ==
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cntkresnetgpu
spec:
  replicas: 1
  template:
    metadata:
      labels:
         app: cntkresnet-gpu
    spec:
      volumes:
      - name: libraries
        hostPath:
          path: /usr/lib/x86_64-linux-gnu
      - name: azurefile
        azureFile:
            secretName: azure-secret
            shareName: data
            readOnly: false      
      containers:
      - name: cntkrestnetgpu
        image: weehyong/cntkresnetgpu
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        ports: 
        - containerPort: 88
        volumeMounts:
        - mountPath: /usr/lib/x86_64-linux-gnu_custom
          name: libraries
        - mountPath: "/data"
          name: azurefile
